version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-southeast-1:482983607458:task-definition/SPB-1:1"
        LoadBalancerInfo:
          ContainerName: "SPB"
          ContainerPort: "80"
        PlatformVersion: "LATEST"
